-- MySQL Script generated by MySQL Workbench
-- 07.11.2021 23:26:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kinokong
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kinokong
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kinokong` DEFAULT CHARACTER SET utf8 ;
USE `kinokong` ;

-- -----------------------------------------------------
-- Table `kinokong`.`db_movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kinokong`.`db_movie` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `movie_name` TEXT NULL DEFAULT NULL,
  `movie_image` TEXT NULL DEFAULT NULL,
  `movie_trailer` TEXT NULL DEFAULT NULL,
  `release_date` VARCHAR(45) NULL DEFAULT NULL,
  `actors` TEXT NULL DEFAULT NULL,
  `movie_genre` VARCHAR(45) NULL DEFAULT NULL,
  `country_of_origin` VARCHAR(45) NULL DEFAULT NULL,
  `user_rating` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1006
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kinokong`.`db_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kinokong`.`db_users` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1005
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
