-- MySQL Script generated by MySQL Workbench
-- Sun Oct 24 21:41:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movie` (
  `movieName` VARCHAR(45) NOT NULL,
  `movieImage` VARCHAR(45) NULL,
  `movieTrailer` VARCHAR(45) NULL,
  `releaseDate` VARCHAR(45) NULL,
  `actors` VARCHAR(45) NULL,
  `movieGenre` VARCHAR(45) NULL,
  `countryOfOrigin` VARCHAR(45) NULL,
  `userRating` INT(1) NULL,
  PRIMARY KEY (`movieName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `email` VARCHAR(32) NULL,
  `password` VARCHAR(20) NOT NULL,
  `firstName` VARCHAR(20) NULL DEFAULT CURRENT_TIMESTAMP,
  `lastName` VARCHAR(20) NULL,
  `phoneNumber` VARCHAR(20) NULL,
  `role` VARCHAR(50) NULL,
  `usercol` VARCHAR(45) NULL);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
